create table products (
	idproducts INT,
	name VARCHAR(50),
	montant VARCHAR(50),
	devise VARCHAR(50),
	imageUrl VARCHAR(50)
);
insert into products (idproducts, name, montant, devise, imageUrl) values (1, 'dg health pain relief pm', '818', 'CNY', 'http://dummyimage.com/189x160.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (2, 'Lyrica', '02645', 'ALL', 'http://dummyimage.com/186x100.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (3, 'CVS Cold Sore Treatment', '496', 'EUR', 'http://dummyimage.com/198x106.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (4, 'DUREZOL', '2', 'VUV', 'http://dummyimage.com/163x123.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (5, 'Ibuprofen', '67', 'EUR', 'http://dummyimage.com/184x164.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (6, 'plus multi symptom cold', '60', 'YER', 'http://dummyimage.com/237x119.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (7, 'Zoledronic Acid', '56327', 'RUB', 'http://dummyimage.com/113x156.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (8, 'Stemphylium sarciniforms', '058', 'CNY', 'http://dummyimage.com/247x129.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (9, 'SALSOLA KALI POLLEN', '6', 'USD', 'http://dummyimage.com/112x131.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (10, 'GlyBURIDE', '5526', 'EUR', 'http://dummyimage.com/184x107.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (11, 'Methocarbamol', '82', 'IDR', 'http://dummyimage.com/129x122.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (12, 'The Gargle', '36', 'PHP', 'http://dummyimage.com/138x150.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (13, 'ECZEMA AND PSORIASIS FREE', '1399', 'BRL', 'http://dummyimage.com/227x171.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (14, 'Vichy Laboratoires Normaderm Daily Pore Unclogging Scrub', '184', 'KMF', 'http://dummyimage.com/154x130.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (15, 'OXYGEN', '3', 'PHP', 'http://dummyimage.com/201x100.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (16, 'Antimicrobial', '23327', 'BIF', 'http://dummyimage.com/219x140.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (17, 'Tobramycin and Dexamethasone', '0346', 'CVE', 'http://dummyimage.com/238x130.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (18, 'Dipyridamole', '3467', 'HRK', 'http://dummyimage.com/139x160.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (19, 'Scar Remover', '43', 'IDR', 'http://dummyimage.com/185x167.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (20, 'EZ Nite Sleep', '34741', 'NZD', 'http://dummyimage.com/228x162.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (21, 'Hickory Pollen Mixture', '832', 'EUR', 'http://dummyimage.com/103x154.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (22, 'CC', '95911', 'PHP', 'http://dummyimage.com/109x103.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (23, 'ROBITUSSIN PEAK COLD MAXIMUM STRENGTH COUGH PLUS CHEST CONGESTION DM', '1', 'AZN', 'http://dummyimage.com/101x154.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (24, 'Ciprodex', '851', 'IDR', 'http://dummyimage.com/165x165.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (25, 'GALZIN', '8315', 'CNY', 'http://dummyimage.com/134x149.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (26, 'Island Breeze Antibacterial Foaming Hand Wash', '5', 'CNY', 'http://dummyimage.com/153x126.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (27, 'Plum', '4', 'ALL', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (28, 'Carbamazepine', '224', 'BRL', 'http://dummyimage.com/105x107.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (29, 'ibuprofen', '3', 'BRL', 'http://dummyimage.com/149x113.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (30, 'Prometh with Codeine', '303', 'CNY', 'http://dummyimage.com/151x126.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (31, 'MAGNESIA PHOSPHORICA', '749', 'THB', 'http://dummyimage.com/237x141.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (32, 'Carvedilol', '63815', 'HNL', 'http://dummyimage.com/159x170.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (33, 'Neutrogena Mineral Sheers', '1', 'CNY', 'http://dummyimage.com/134x154.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (34, 'Amoxicillin', '2015', 'EUR', 'http://dummyimage.com/206x116.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (35, 'Johnson Grass', '840', 'PHP', 'http://dummyimage.com/196x179.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (36, 'Baby Nighttime Tiny Cold', '2258', 'SEK', 'http://dummyimage.com/129x147.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (37, 'Arroyo Willow', '75', 'EUR', 'http://dummyimage.com/118x133.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (38, 'COUMADIN', '07', 'RUB', 'http://dummyimage.com/214x129.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (39, 'Alcohol Free HAND SANITIZER', '4608', 'SEK', 'http://dummyimage.com/214x170.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (40, 'Isosorbide Dinitrate', '821', 'VND', 'http://dummyimage.com/204x154.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (41, 'Long Lasting Finish with Comfort Serum', '40', 'EUR', 'http://dummyimage.com/148x110.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (42, 'NEOSPORIN G.U.', '1', 'CNY', 'http://dummyimage.com/194x138.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (43, 'valsartan and hydrochlorothiazide', '0876', 'JPY', 'http://dummyimage.com/239x179.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (44, 'LBEL MAXIMUM COMFORT AND LONG-LASTING FOUNDATION SPF 10', '67', 'CNY', 'http://dummyimage.com/237x108.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (45, 'Claritin', '6', 'PHP', 'http://dummyimage.com/208x167.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (46, 'Cholestyramine', '60870', 'RUB', 'http://dummyimage.com/187x113.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (47, 'Modafinil', '69919', 'EUR', 'http://dummyimage.com/127x177.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (48, 'Zosyn', '80463', 'CRC', 'http://dummyimage.com/110x169.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (49, 'Desloratadine', '630', 'PHP', 'http://dummyimage.com/139x136.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (50, 'Neutrogena Healthy Skin Primer', '539', 'EUR', 'http://dummyimage.com/153x139.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (51, 'PAULAS CHOICE HYDRALIGHT SHINE-FREE DAILY MINERAL COMPLEX Broad Spectrum SPF 30', '58621', 'CNY', 'http://dummyimage.com/194x173.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (52, 'Desmopressin Acetate', '27096', 'EUR', 'http://dummyimage.com/136x135.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (53, 'Glipizide', '273', 'CNY', 'http://dummyimage.com/163x113.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (54, 'Dukal Sterile Alcohol Prep Pad', '3', 'EUR', 'http://dummyimage.com/237x108.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (55, 'Stila CC Color Correcting Broad-Spectrum SPF 20', '681', 'UGX', 'http://dummyimage.com/155x147.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (56, 'Head and Shoulders', '5740', 'CNY', 'http://dummyimage.com/218x125.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (57, 'Lovastatin', '89', 'PHP', 'http://dummyimage.com/155x160.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (58, 'Cultivated Rye', '533', 'GMD', 'http://dummyimage.com/233x166.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (59, 'Food - Plant Source, Almond Prunus amygdalus', '1', 'CZK', 'http://dummyimage.com/161x127.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (60, 'Nivea For Men Age Defying Face Moisturizer', '6040', 'BAM', 'http://dummyimage.com/162x161.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (61, 'Betamethasone Dipropionate', '0982', 'CNY', 'http://dummyimage.com/203x141.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (62, 'Oxygen-Nitrogen Mixture', '474', 'CNY', 'http://dummyimage.com/226x136.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (63, 'Risperidone', '9083', 'PLN', 'http://dummyimage.com/138x156.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (64, 'RISPERIDONE', '39', 'PHP', 'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (65, 'Citroma', '2880', 'IDR', 'http://dummyimage.com/146x172.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (66, 'Phentermine Hydrochloride', '2', 'IDR', 'http://dummyimage.com/112x172.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (67, 'Ampicillin and Sulbactam', '2204', 'RUB', 'http://dummyimage.com/134x171.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (68, 'Venlafaxine', '53', 'HKD', 'http://dummyimage.com/111x109.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (69, 'SUPRESS-PE', '10', 'EUR', 'http://dummyimage.com/186x113.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (70, 'Gabapentin', '4', 'PHP', 'http://dummyimage.com/235x159.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (71, 'Tramadol Hydrochloride and Acetaminophen', '8726', 'EUR', 'http://dummyimage.com/185x146.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (72, 'Folic Acid', '6731', 'CNY', 'http://dummyimage.com/143x111.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (73, 'Clean Apple', '6', 'IDR', 'http://dummyimage.com/124x131.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (74, 'Sertraline Hydrochloride', '511', 'KZT', 'http://dummyimage.com/194x173.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (75, 'Quetiapine fumarate', '9748', 'CNY', 'http://dummyimage.com/222x102.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (76, 'Healing Support', '82', 'RUB', 'http://dummyimage.com/193x158.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (77, 'Dairy Allergy Relief', '67', 'GTQ', 'http://dummyimage.com/199x148.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (78, 'Guanfacine', '71', 'PEN', 'http://dummyimage.com/228x117.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (79, 'PreNatal Vitamins Plus', '8', 'CNY', 'http://dummyimage.com/147x177.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (80, 'Oxygen', '9', 'PLN', 'http://dummyimage.com/213x163.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (81, 'Motion Sickness II', '844', 'CNY', 'http://dummyimage.com/155x139.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (82, 'Trazodone Hydrochloride', '14867', 'EUR', 'http://dummyimage.com/161x163.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (83, 'MELALEUCA QUINQUENERVIA POLLEN', '8', 'THB', 'http://dummyimage.com/186x119.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (84, 'Concealing Spot Treatment', '83692', 'USD', 'http://dummyimage.com/152x138.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (85, 'good neighbor pharmacy miconazole 3', '8', 'PLN', 'http://dummyimage.com/194x144.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (86, 'CORISIN ARTHRITIS PAIN RELIEF', '2', 'CZK', 'http://dummyimage.com/212x176.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (87, 'OXYGEN', '3', 'CZK', 'http://dummyimage.com/116x102.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (88, 'IPKN HYDRO AND PORE BB 02 MEDIUM', '4', 'MXN', 'http://dummyimage.com/120x103.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (89, 'ENBREL', '76244', 'HRK', 'http://dummyimage.com/166x170.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (90, 'FUROSEMIDE', '395', 'HTG', 'http://dummyimage.com/100x101.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (91, 'Sinusalia', '8101', 'CNY', 'http://dummyimage.com/191x139.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (92, 'FUSARIUM OXYSPORUM VASINFECTUM', '099', 'BGN', 'http://dummyimage.com/153x151.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (93, 'Trazodone Hydrochloride', '644', 'CNY', 'http://dummyimage.com/124x127.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (94, 'Isosorbide Dinitrate', '5', 'CNY', 'http://dummyimage.com/231x120.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (95, 'Nortriptyline Hydrochloride', '227', 'CNY', 'http://dummyimage.com/245x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (96, 'ck one airlight pressed powder spf 15', '641', 'BRL', 'http://dummyimage.com/125x143.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (97, 'Quetiapine fumarate', '880', 'JPY', 'http://dummyimage.com/140x124.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (98, 'Cocklebur', '67900', 'COP', 'http://dummyimage.com/177x178.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (99, 'Megestrol Acetate', '2574', 'BRL', 'http://dummyimage.com/217x108.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (100, 'Neutrogena Oil Free Acne Stress Control', '82', 'IDR', 'http://dummyimage.com/218x154.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (101, 'Lactulose', '11023', 'RUB', 'http://dummyimage.com/145x130.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (102, 'Food - Plant Source, Soybean Glycine soja', '4356', 'PEN', 'http://dummyimage.com/183x167.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (103, 'Spironolactone', '75', 'IDR', 'http://dummyimage.com/216x169.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (104, 'Stomach Cramps 1', '73', 'IDR', 'http://dummyimage.com/202x153.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (105, 'Aplicare Physicians Antibacterial', '11091', 'PLN', 'http://dummyimage.com/120x107.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (106, 'CAPASTAT SULFATE', '8', 'IDR', 'http://dummyimage.com/100x116.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (107, 'WhiskCare 375', '42943', 'PHP', 'http://dummyimage.com/167x148.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (108, 'Amantadine Hydrochloride', '19', 'CNY', 'http://dummyimage.com/133x132.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (109, 'AMBROSIA ARTEMISIIFOLIA POLLEN', '97', 'CNY', 'http://dummyimage.com/105x148.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (110, 'Buspirone Hydrochloride', '6', 'YER', 'http://dummyimage.com/136x105.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (111, 'TREE OF HEAVEN POLLEN', '588', 'AMD', 'http://dummyimage.com/154x173.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (112, 'HYDRO SPLASH BB', '74', 'IQD', 'http://dummyimage.com/185x113.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (113, 'Asparagus', '85', 'IDR', 'http://dummyimage.com/210x116.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (114, 'HAND AND NATURE SANITIZER', '6', 'PHP', 'http://dummyimage.com/209x174.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (115, 'Urecholine', '4488', 'TZS', 'http://dummyimage.com/219x109.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (116, 'Isosulfan Blue', '36', 'CNY', 'http://dummyimage.com/194x177.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (117, 'Breast Inflammations and Discomforts', '5', 'PLN', 'http://dummyimage.com/127x146.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (118, 'Spiny Pigweed', '703', 'TJS', 'http://dummyimage.com/113x118.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (119, 'MicroMousse II Alcohol Free Hand Sanitizing Foam', '1118', 'XAF', 'http://dummyimage.com/173x108.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (120, 'Lamb Quarters', '863', 'CNY', 'http://dummyimage.com/125x161.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (121, 'Levora', '86', 'USD', 'http://dummyimage.com/173x125.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (122, 'Tri-Estarylla', '26', 'HUF', 'http://dummyimage.com/228x102.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (123, 'Tryptophan', '76', 'GTQ', 'http://dummyimage.com/102x136.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (124, 'VITALUMIERE', '075', 'RUB', 'http://dummyimage.com/197x105.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (125, 'Extra Strength Rapid Release Acetaminophen PM', '3', 'MXN', 'http://dummyimage.com/195x131.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (126, 'Ibuprofen', '7768', 'EUR', 'http://dummyimage.com/131x130.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (127, 'NAVI MAXON Sirin Doctor', '3', 'EUR', 'http://dummyimage.com/157x176.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (128, 'Good Sense Nasal Decongestant PE', '1', 'RUB', 'http://dummyimage.com/232x169.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (129, 'CVS Pharmacy', '75668', 'EUR', 'http://dummyimage.com/223x152.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (130, 'Ibuprofen', '45248', 'CAD', 'http://dummyimage.com/150x114.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (131, 'REYATAZ', '5', 'IDR', 'http://dummyimage.com/119x114.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (132, 'Griseofulvin', '48', 'EUR', 'http://dummyimage.com/209x157.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (133, 'Duloxetine', '25099', 'CNY', 'http://dummyimage.com/187x157.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (134, 'Lisinopril', '0621', 'CNY', 'http://dummyimage.com/112x174.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (135, 'Leader', '7', 'CZK', 'http://dummyimage.com/209x117.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (136, 'Wal Fex 24 Hour Allergy', '7365', 'CRC', 'http://dummyimage.com/110x138.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (137, 'simvastatin', '703', 'EUR', 'http://dummyimage.com/215x156.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (138, 'Chlorpromazine Hydrochloride', '45', 'CNY', 'http://dummyimage.com/181x169.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (139, 'Lachesis Belladonna', '66427', 'RUB', 'http://dummyimage.com/125x105.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (140, 'Alka-Seltzer Plus Cold and Cough Formula', '505', 'COP', 'http://dummyimage.com/214x111.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (141, 'Venlafaxine', '30', 'UAH', 'http://dummyimage.com/130x101.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (142, 'SEPHORA Skin Perfect CC Sunscreen Broad Spectrum SPF 20 LIGHT', '7', 'EUR', 'http://dummyimage.com/108x174.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (143, 'Mandragora e rad. 2', '5051', 'XAF', 'http://dummyimage.com/238x147.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (144, 'Olanzapine', '19013', 'KZT', 'http://dummyimage.com/159x124.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (145, 'BETULA NIGRA POLLEN', '33422', 'MYR', 'http://dummyimage.com/209x170.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (146, 'topcare feminine', '26234', 'EUR', 'http://dummyimage.com/222x162.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (147, 'Sodium Sulfacetamide and Sulfur', '88055', 'CNY', 'http://dummyimage.com/213x106.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (148, 'COLDS COUGHS', '115', 'IDR', 'http://dummyimage.com/193x119.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (149, 'Fosinopril Sodium', '71550', 'CNY', 'http://dummyimage.com/247x159.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (150, 'Bupropion Hydrochloride', '427', 'MNT', 'http://dummyimage.com/233x146.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (151, 'FENTANYL TRANSDERMAL SYSTEM', '173', 'ARS', 'http://dummyimage.com/154x132.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (152, 'A. Dust', '34881', 'IRR', 'http://dummyimage.com/125x102.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (153, 'ibuprofen', '5554', 'CNY', 'http://dummyimage.com/163x154.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (154, 'Gas Relief', '3', 'EUR', 'http://dummyimage.com/136x149.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (155, 'Long Acting Tussin Cough Gels', '127', 'AZN', 'http://dummyimage.com/122x124.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (156, 'ESIKA', '4192', 'ZAR', 'http://dummyimage.com/107x152.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (157, 'Triacting Night Time', '221', 'RUB', 'http://dummyimage.com/169x103.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (158, 'equate Acid Controller', '68091', 'PLN', 'http://dummyimage.com/111x131.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (159, 'Calcium Chloride', '0', 'MAD', 'http://dummyimage.com/196x143.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (160, 'Milk of Magnesia Mint', '0072', 'JPY', 'http://dummyimage.com/198x110.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (161, 'CEFTRIAXONE', '40', 'USD', 'http://dummyimage.com/196x136.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (162, 'Alert', '125', 'SEK', 'http://dummyimage.com/166x144.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (163, 'Uricalm', '971', 'CNY', 'http://dummyimage.com/187x129.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (164, 'Risperidone', '9811', 'SYP', 'http://dummyimage.com/108x159.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (165, 'Colgate', '4', 'PKR', 'http://dummyimage.com/128x173.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (166, 'Super Aqua Night', '699', 'CNY', 'http://dummyimage.com/173x117.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (167, 'PROMETHAZINE WITH CODEINE', '1621', 'ARS', 'http://dummyimage.com/197x149.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (168, 'Amoxicillin', '74', 'AZN', 'http://dummyimage.com/118x155.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (169, 'Sodium FluorideF 18', '7', 'IDR', 'http://dummyimage.com/173x128.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (170, 'CIPROFLOXACIN', '39894', 'CNY', 'http://dummyimage.com/234x149.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (171, 'Lombard Poplar Pollen', '94852', 'LKR', 'http://dummyimage.com/188x126.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (172, 'Lunesta', '8740', 'EUR', 'http://dummyimage.com/210x114.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (173, 'Hyoscyamine Sulfate', '112', 'IDR', 'http://dummyimage.com/211x120.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (174, 'Sumatriptan', '5', 'CZK', 'http://dummyimage.com/106x125.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (175, 'ATORVASTATIN CALCIUM', '80', 'USD', 'http://dummyimage.com/107x149.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (176, 'Anti-Bacterial Hand Gel Pink Lemonade', '80030', 'RUB', 'http://dummyimage.com/130x107.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (177, 'Lidocaine Hydrochloride', '426', 'IDR', 'http://dummyimage.com/237x128.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (178, 'Sucralfate', '500', 'ALL', 'http://dummyimage.com/124x140.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (179, 'Salsalate', '2', 'SEK', 'http://dummyimage.com/157x108.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (180, 'Hydrocodone Bitartrate and Homatropine Methylbromide', '99', 'MXN', 'http://dummyimage.com/125x107.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (181, 'Mirtazapine', '47', 'RUB', 'http://dummyimage.com/126x134.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (182, 'CLARINS HydraQuench Tinted Moisturizer Broad Spectrum SPF 6 02 BEIGE', '2994', 'EGP', 'http://dummyimage.com/179x175.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (183, 'Sucralfate', '64057', 'AFN', 'http://dummyimage.com/145x121.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (184, 'LBEL COULEUR LUXE AMPLIFIER XP', '12', 'CNY', 'http://dummyimage.com/140x100.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (185, 'Citalopram Hydrobromide', '0', 'PEN', 'http://dummyimage.com/197x160.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (186, 'Antimicrobial Foam', '3', 'CNY', 'http://dummyimage.com/194x153.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (187, 'Good Sense Childrens Cold and Cough', '5', 'IDR', 'http://dummyimage.com/102x171.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (188, 'Ivory Always color stay-on Makeup Broad Spectrum SPF 15', '91779', 'UZS', 'http://dummyimage.com/118x101.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (189, 'Simcor', '1', 'PEN', 'http://dummyimage.com/127x173.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (190, 'Bacitracin', '3360', 'RUB', 'http://dummyimage.com/112x125.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (191, 'SHISEIDO RADIANT LIFTING FOUNDATION', '1', 'BRL', 'http://dummyimage.com/117x178.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (192, 'ZIT ZAPPER', '904', 'IDR', 'http://dummyimage.com/194x107.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (193, 'Amlodipine and Benazepril Hydrochloride', '797', 'PLN', 'http://dummyimage.com/140x141.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (194, 'zoledronic acid', '8', 'PHP', 'http://dummyimage.com/144x179.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (195, 'Treatment Set TS331796', '114', 'ILS', 'http://dummyimage.com/110x159.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (196, 'SHISEIDO SHEER AND PERFECT COMPACT (REFILL)', '96', 'IDR', 'http://dummyimage.com/111x152.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (197, 'Cinnamon', '6', 'COP', 'http://dummyimage.com/129x147.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (198, 'Lyrica', '6', 'CZK', 'http://dummyimage.com/170x165.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (199, 'Paroxetine', '5596', 'CZK', 'http://dummyimage.com/120x158.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (200, 'FEIBA', '6', 'CNY', 'http://dummyimage.com/138x118.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (201, 'Sesame', '18386', 'EUR', 'http://dummyimage.com/171x116.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (202, 'Sani Professional Brand Sani-Hands for Kids', '91', 'EUR', 'http://dummyimage.com/172x109.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (203, 'HYCAMTIN', '118', 'EUR', 'http://dummyimage.com/235x166.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (204, 'OXYGEN', '888', 'PLN', 'http://dummyimage.com/140x136.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (205, 'Citalopram Hydrobromide', '9534', 'TND', 'http://dummyimage.com/177x134.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (206, 'Terbutaline Sulfate', '19', 'CNY', 'http://dummyimage.com/145x117.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (207, 'Gas Relief', '575', 'MNT', 'http://dummyimage.com/236x112.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (208, 'Allopurinol', '8', 'IDR', 'http://dummyimage.com/106x103.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (209, 'Lamotrigine', '07', 'CNY', 'http://dummyimage.com/135x176.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (210, 'Epiphysis Plumbum', '92', 'UAH', 'http://dummyimage.com/179x179.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (211, 'Niravam', '56032', 'EUR', 'http://dummyimage.com/161x139.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (212, 'family wellness laxative', '6', 'TND', 'http://dummyimage.com/103x118.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (213, 'POTIGA', '72752', 'CDF', 'http://dummyimage.com/175x167.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (214, 'Glytone acne treatment flesh tinted acne', '0633', 'CNY', 'http://dummyimage.com/217x110.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (215, 'Head and Shoulders', '29867', 'SEK', 'http://dummyimage.com/137x162.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (216, 'rizatriptan benzoate', '693', 'BRL', 'http://dummyimage.com/246x117.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (217, 'CAPTURE TOTALE COMPACT RADIANCE RESTORING LINE SMOOTHING MAKEUP SPF 20 021 Linen', '19675', 'RUB', 'http://dummyimage.com/246x162.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (218, 'SMITH BROS NON-DROWSY MULTI-SYMPTOM COLD and FLU', '0', 'NGN', 'http://dummyimage.com/196x144.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (219, 'Candida albicans', '16544', 'CNY', 'http://dummyimage.com/111x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (220, 'Triple Antibiotic Plus', '2', 'BYR', 'http://dummyimage.com/207x166.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (221, 'OXYGEN', '412', 'COP', 'http://dummyimage.com/128x124.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (222, 'NU-COPD', '4567', 'ALL', 'http://dummyimage.com/174x159.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (223, 'Vancomycin Hydrochloride', '41876', 'RUB', 'http://dummyimage.com/102x174.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (224, 'mucus er', '437', 'EUR', 'http://dummyimage.com/216x129.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (225, 'Reglan', '391', 'CNY', 'http://dummyimage.com/244x119.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (226, 'KOMBIGLYZE', '48', 'CNY', 'http://dummyimage.com/119x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (227, 'Menstrual Relief', '723', 'PKR', 'http://dummyimage.com/232x114.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (228, 'Molds, Rusts and Smuts, Cephalosporium acremonium', '126', 'ILS', 'http://dummyimage.com/145x174.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (229, 'Isosorbide Mononitrate', '9', 'RUB', 'http://dummyimage.com/239x179.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (230, 'SEROQUEL', '7', 'SEK', 'http://dummyimage.com/129x153.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (231, 'BUDESONIDE', '6', 'PYG', 'http://dummyimage.com/104x138.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (232, 'KIDS FIRST AID', '95165', 'RUB', 'http://dummyimage.com/145x155.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (233, 'Sulfamethoxazole and Trimethoprim', '8997', 'ARS', 'http://dummyimage.com/122x175.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (234, 'OBAGI-C RX SYSTEM C-SUNGUARD', '8273', 'BOB', 'http://dummyimage.com/242x162.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (235, 'Water Oak', '8', 'EUR', 'http://dummyimage.com/120x151.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (236, 'Nabumetone', '0189', 'TND', 'http://dummyimage.com/229x101.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (237, 'Lorazepam', '61', 'AFN', 'http://dummyimage.com/110x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (238, 'Soma', '41', 'BRL', 'http://dummyimage.com/166x155.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (239, 'Colgate Sparkling White CinnaMint Fluoride', '1330', 'UAH', 'http://dummyimage.com/196x137.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (240, 'Kiehls Since 1851 Facial Fuel UV Guard', '9', 'CNY', 'http://dummyimage.com/128x177.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (241, 'Blistex', '9', 'PLN', 'http://dummyimage.com/151x173.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (242, 'PHOENIX HEALTHCARE SOLUTIONS, LLC', '0', 'BSD', 'http://dummyimage.com/113x166.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (243, 'Good Neighbor Pain Relief', '3', 'EUR', 'http://dummyimage.com/226x180.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (244, 'Triamcinolone Acetonide', '9535', 'IDR', 'http://dummyimage.com/211x161.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (245, 'Temazepam', '640', 'SEK', 'http://dummyimage.com/143x167.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (246, 'PediaCare Childrens Plus Cough and Runny Nose', '576', 'CNY', 'http://dummyimage.com/142x156.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (247, 'Sertraline Hydrochloride', '26341', 'EUR', 'http://dummyimage.com/238x174.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (248, 'Hydrogen Peroxide', '44', 'RUB', 'http://dummyimage.com/104x129.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (249, 'Detrol', '46296', 'XAF', 'http://dummyimage.com/155x145.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (250, 'INVEGA', '030', 'VND', 'http://dummyimage.com/105x115.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (251, 'Aspen', '95', 'CNY', 'http://dummyimage.com/134x180.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (252, 'Glipizide', '78561', 'IDR', 'http://dummyimage.com/147x165.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (253, 'Seb Prev', '23565', 'BGN', 'http://dummyimage.com/221x146.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (254, 'Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate and Amphetamine Sulfate', '1355', 'PHP', 'http://dummyimage.com/121x113.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (255, 'Ondansetron', '4', 'MMK', 'http://dummyimage.com/194x127.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (256, 'Bisoprolol Fumarate', '5506', 'EUR', 'http://dummyimage.com/158x148.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (257, 'No7 Beautiful Skin Oil Free Skin Protector All Skin Types SPF 25', '8', 'SEK', 'http://dummyimage.com/217x125.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (258, 'Topiramate', '4', 'KWD', 'http://dummyimage.com/108x132.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (259, 'LAMICTAL', '25244', 'CNY', 'http://dummyimage.com/159x160.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (260, 'Topotecan Hydrochloride', '653', 'VND', 'http://dummyimage.com/126x139.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (261, 'Walgreens Nerve Pain Relief', '9', 'IDR', 'http://dummyimage.com/221x171.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (262, 'LenzaPatch', '4', 'NGN', 'http://dummyimage.com/210x136.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (263, 'allergy and congestion relief', '53', 'KGS', 'http://dummyimage.com/209x137.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (264, 'simple pleasures', '6', 'CNY', 'http://dummyimage.com/149x139.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (265, 'AMRIX', '09464', 'CNY', 'http://dummyimage.com/169x104.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (266, 'Isopto Homatropine', '20', 'IDR', 'http://dummyimage.com/112x118.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (267, 'Acetaminophen,Dextromethorphan,Doxylamine', '27', 'CNY', 'http://dummyimage.com/146x163.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (268, 'Pleo Pef', '74', 'IDR', 'http://dummyimage.com/112x129.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (269, 'SENSAI CELLULAR PERFORMANCE POWDER FOUNDATION', '655', 'PHP', 'http://dummyimage.com/211x135.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (270, 'Lym D', '5', 'CZK', 'http://dummyimage.com/128x161.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (271, 'Traumeel', '36', 'CNY', 'http://dummyimage.com/145x179.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (272, 'Genlabs Strike Bac Antibacterial Handsoap', '3', 'NPR', 'http://dummyimage.com/198x105.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (273, 'Valacyclovir Hydrochloride', '79', 'BRL', 'http://dummyimage.com/207x151.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (274, 'LBEL Couleur Luxe Rouge Amplifier XP amplifying SPF 15', '3', 'IDR', 'http://dummyimage.com/152x135.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (275, 'Oxaliplatin', '6097', 'RUB', 'http://dummyimage.com/108x149.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (276, 'CYZONE', '677', 'CNY', 'http://dummyimage.com/214x139.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (277, 'promethazine hydrochloride', '84339', 'CNY', 'http://dummyimage.com/232x119.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (278, 'Lisinopril', '5762', 'CNY', 'http://dummyimage.com/237x179.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (279, 'Quik-Care', '0733', 'IDR', 'http://dummyimage.com/214x137.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (280, 'Esika', '909', 'MXN', 'http://dummyimage.com/160x171.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (281, 'careone hair regrowth treatment', '915', 'PHP', 'http://dummyimage.com/186x168.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (282, 'Topotecan Hydrochloride', '099', 'RUB', 'http://dummyimage.com/228x173.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (283, 'Origins', '2248', 'MNT', 'http://dummyimage.com/129x174.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (284, 'good neighbor pharmacy anti nausea', '94', 'ARS', 'http://dummyimage.com/125x164.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (285, 'Atorvastatin Calcium', '7174', 'RUB', 'http://dummyimage.com/182x110.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (286, 'Dukal Alcohol Prep Pad', '243', 'PHP', 'http://dummyimage.com/107x126.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (287, 'BLACK OAK POLLEN', '5', 'CZK', 'http://dummyimage.com/162x175.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (288, 'Clarithromycin', '083', 'UAH', 'http://dummyimage.com/129x171.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (289, 'SOMA Hyulgihwan', '91', 'COP', 'http://dummyimage.com/250x119.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (290, 'Anacin', '549', 'BDT', 'http://dummyimage.com/237x148.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (291, 'Prednisone', '57824', 'RUB', 'http://dummyimage.com/199x146.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (292, 'Motion-Time', '3475', 'USD', 'http://dummyimage.com/145x102.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (293, 'Orajel Instant Pain Relief for Severe Toothache', '01988', 'MXN', 'http://dummyimage.com/166x168.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (294, 'Extra Strength Non-Aspirin PM', '3', 'CNY', 'http://dummyimage.com/149x164.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (295, 'IMODIUM', '7924', 'ARS', 'http://dummyimage.com/207x129.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (296, 'CLE DE PEAU BEAUTE SILKY FOUNDATION I', '9343', 'NOK', 'http://dummyimage.com/151x152.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (297, 'Balsalazide Disodium', '0', 'AFN', 'http://dummyimage.com/170x118.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (298, 'MUSCLE SORENESS HEADACHE', '2119', 'USD', 'http://dummyimage.com/230x142.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (299, 'Childrens Earache Relief', '29', 'PEN', 'http://dummyimage.com/127x166.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (300, 'LBel Paris', '16065', 'THB', 'http://dummyimage.com/178x122.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (301, 'Aristospan', '88481', 'USD', 'http://dummyimage.com/157x155.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (302, 'Lymph Spleen Combo', '38', 'CNY', 'http://dummyimage.com/204x121.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (303, 'Gabapentin', '36744', 'BGN', 'http://dummyimage.com/169x140.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (304, 'Nisoldipine', '9173', 'FJD', 'http://dummyimage.com/126x151.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (305, 'Penicillium notatum', '3', 'PHP', 'http://dummyimage.com/217x152.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (306, 'Risperidone', '49815', 'PHP', 'http://dummyimage.com/194x132.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (307, 'SPINY PIGWEED POLLEN', '33', 'PHP', 'http://dummyimage.com/207x105.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (308, 'Day Time with PE', '083', 'JOD', 'http://dummyimage.com/161x101.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (309, 'Vida Mia Hand Sanitizer', '44801', 'NGN', 'http://dummyimage.com/135x115.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (310, 'Azuro', '0376', 'UAH', 'http://dummyimage.com/201x127.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (311, 'GAP Favorite Lip Balm', '9', 'RUB', 'http://dummyimage.com/160x176.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (312, 'Terbinafine Hydrochloride', '0535', 'VEF', 'http://dummyimage.com/105x127.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (313, 'Coppertone Sport High Performance Faces', '925', 'UAH', 'http://dummyimage.com/155x157.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (314, 'Baby Nighttime Tiny Cold', '590', 'EUR', 'http://dummyimage.com/217x174.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (315, 'Trazodone Hydrochloride', '84', 'CNY', 'http://dummyimage.com/146x155.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (316, 'Bethanechol Chloride', '4', 'GBP', 'http://dummyimage.com/157x134.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (317, 'Propranolol Hydrochloride', '53628', 'CNY', 'http://dummyimage.com/160x141.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (318, 'Maybelline New York Instant Age Rewind Eraser', '9025', 'CNY', 'http://dummyimage.com/241x172.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (319, 'Doxycycline', '8905', 'UZS', 'http://dummyimage.com/112x114.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (320, 'Topotecan Hydrochloride', '6', 'GTQ', 'http://dummyimage.com/188x172.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (321, 'LAMOTRIGINE', '2096', 'PHP', 'http://dummyimage.com/113x114.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (322, 'CellCept', '30', 'IDR', 'http://dummyimage.com/217x150.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (323, 'Lymph Plus', '2226', 'NGN', 'http://dummyimage.com/245x156.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (324, 'Glipizide', '7823', 'ARS', 'http://dummyimage.com/229x104.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (325, 'Equaline Mucus ER', '8971', 'EUR', 'http://dummyimage.com/126x147.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (326, 'healthy accents aspirin', '192', 'PHP', 'http://dummyimage.com/219x180.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (327, 'SmartMouth', '5778', 'MYR', 'http://dummyimage.com/209x127.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (328, 'IOPE AIR CUSHION XP', '222', 'PLN', 'http://dummyimage.com/161x106.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (329, 'Neutrogena Healthy Skin Face', '7389', 'BRL', 'http://dummyimage.com/197x180.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (330, 'Pravastatin Sodium', '0', 'ALL', 'http://dummyimage.com/145x144.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (331, 'EPIPEN JR', '1432', 'EUR', 'http://dummyimage.com/248x105.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (332, 'Naproxen', '65', 'CNY', 'http://dummyimage.com/221x109.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (333, 'Red Maple', '260', 'PEN', 'http://dummyimage.com/100x121.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (334, 'HAVRIX', '1239', 'IDR', 'http://dummyimage.com/123x170.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (335, 'TAMSULOSIN HYDROCHLORIDE', '3783', 'CNY', 'http://dummyimage.com/222x113.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (336, 'Aureobasidium pullulans', '81', 'IDR', 'http://dummyimage.com/167x156.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (337, 'Healthy Accents Pain Relief', '18', 'BRL', 'http://dummyimage.com/100x151.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (338, 'Oxygen', '3', 'EUR', 'http://dummyimage.com/159x170.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (339, 'FASLODEX', '1134', 'RUB', 'http://dummyimage.com/134x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (340, 'Ciprofloxacin hydrochloride', '19', 'PKR', 'http://dummyimage.com/125x140.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (341, 'Glucotrol XL', '95', 'PLN', 'http://dummyimage.com/245x128.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (342, 'Ibutilide Fumarate', '72140', 'CUP', 'http://dummyimage.com/119x174.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (343, 'Metoprolol succinate', '6270', 'SYP', 'http://dummyimage.com/163x155.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (344, 'SOTALOL HYDROCHLORIDE', '10', 'CNY', 'http://dummyimage.com/221x178.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (345, 'CD DiorSnow UV Shield Transluscent - SPF50', '651', 'USD', 'http://dummyimage.com/152x109.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (346, 'Mirtazapine', '01', 'IRR', 'http://dummyimage.com/205x122.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (347, 'Pravastatin Sodium', '8', 'CNY', 'http://dummyimage.com/115x179.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (348, 'good neighbor pharmacy nicotine', '90', 'JPY', 'http://dummyimage.com/218x127.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (349, 'Enalapril Maleate', '88549', 'JPY', 'http://dummyimage.com/192x172.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (350, 'Ondansetron', '88899', 'CNY', 'http://dummyimage.com/138x172.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (351, 'hydroxyzine pamoate', '21', 'EUR', 'http://dummyimage.com/103x146.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (352, 'LBel', '81368', 'CNY', 'http://dummyimage.com/238x105.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (353, 'flormar Foundation Sunscreen Broad Spectrum SPF 20 LF01 PORCELAIN', '04', 'AFN', 'http://dummyimage.com/133x153.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (354, 'Sunmark Arthritis Pain Reliever', '8', 'EGP', 'http://dummyimage.com/197x162.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (355, 'SHISEIDO THE MAKEUP FOUNDATION', '0', 'PHP', 'http://dummyimage.com/153x176.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (356, 'Cedax', '1439', 'CNY', 'http://dummyimage.com/160x124.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (357, 'SATINIQUE ANTI-DANDRUFF for dry, irritated scalp', '1495', 'CNY', 'http://dummyimage.com/245x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (358, 'Metoclopramide', '5398', 'VND', 'http://dummyimage.com/150x111.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (359, 'MOZI-Q', '2', 'CNY', 'http://dummyimage.com/141x125.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (360, 'KLEENEX Antimicrobial Foam Skin Cleanser', '016', 'CNY', 'http://dummyimage.com/227x179.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (361, 'Omeprazole', '84', 'EUR', 'http://dummyimage.com/113x173.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (362, 'Venlafaxine', '435', 'CNY', 'http://dummyimage.com/133x106.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (363, 'Poplar', '76058', 'PHP', 'http://dummyimage.com/246x177.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (364, 'THERAMAX ALLERGY RELIEF NASAL', '99', 'EUR', 'http://dummyimage.com/186x163.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (365, 'Everyday Clean Dandruff', '7422', 'CNY', 'http://dummyimage.com/233x116.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (366, 'Acetaminophen', '3', 'PHP', 'http://dummyimage.com/123x152.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (367, 'Hydrogen Peroxide', '19', 'JMD', 'http://dummyimage.com/141x162.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (368, 'Grass Smut Mixture', '7', 'CNY', 'http://dummyimage.com/178x157.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (369, 'ZENPEP', '5', 'MAD', 'http://dummyimage.com/235x150.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (370, 'Vancocin', '947', 'PEN', 'http://dummyimage.com/165x103.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (371, 'Dulcolax', '307', 'MXN', 'http://dummyimage.com/165x125.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (372, 'Sivil 40 (Number 24)', '1', 'RUB', 'http://dummyimage.com/140x144.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (373, 'Polymyxin B Sulfate and Trimethoprim', '2', 'IDR', 'http://dummyimage.com/231x153.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (374, 'acyclovir', '6706', 'ARS', 'http://dummyimage.com/205x159.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (375, 'Pacific', '490', 'CNY', 'http://dummyimage.com/205x148.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (376, 'Coreg', '88147', 'RUB', 'http://dummyimage.com/170x148.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (377, 'Novolin', '534', 'CNY', 'http://dummyimage.com/228x120.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (378, 'IT RADIANT CC IN MELTING FOUNDATION', '03621', 'BRL', 'http://dummyimage.com/228x159.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (379, 'benztropine mesylate', '7', 'USD', 'http://dummyimage.com/118x117.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (380, 'Coralite ALCOHOL PADS', '55', 'USD', 'http://dummyimage.com/147x177.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (381, 'Hydrocodone Bitartrate and Acetaminophen', '31835', 'CNY', 'http://dummyimage.com/123x165.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (382, 'HEMORRHOID RELIEF', '25893', 'PHP', 'http://dummyimage.com/224x155.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (383, 'AMOREPACIFIC', '541', 'RUB', 'http://dummyimage.com/115x174.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (384, 'Lisinopril and Hydrochlorothiazide', '95005', 'ALL', 'http://dummyimage.com/116x152.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (385, 'AQUA COLLAGEN SOLUTION MARINE HYDROGEL EYE', '56757', 'EUR', 'http://dummyimage.com/193x161.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (386, 'ERY-TAB', '44289', 'CNY', 'http://dummyimage.com/228x100.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (387, 'CPD', '71', 'XOF', 'http://dummyimage.com/119x107.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (388, 'CD DIORSNOW UV SHIELD Brightening Illuminating UV Protection With Sunscreen TRANSLUCENT BROAD SPECTRUM SPF 50', '290', 'EUR', 'http://dummyimage.com/133x138.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (389, 'La Roche Posay Laboratoire Dermatologique Anthelios 50 Mineral Body Broad Spectrum SPF 50 Ultra Light Sunscreen', '718', 'EUR', 'http://dummyimage.com/135x100.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (390, 'Cover Fx Blemish Treatment Concealer N Med-Deep', '203', 'CNY', 'http://dummyimage.com/180x135.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (391, 'Anti-Bacterial Hand', '7433', 'EUR', 'http://dummyimage.com/212x176.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (392, 'Melaleuca', '7', 'BRL', 'http://dummyimage.com/195x112.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (393, 'Lidocaine Hydrochloride', '1', 'USD', 'http://dummyimage.com/167x104.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (394, 'PredniSONE', '1', 'VEF', 'http://dummyimage.com/100x109.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (395, 'RISPERIDONE', '8', 'KPW', 'http://dummyimage.com/158x147.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (396, 'Advanced Hand Sanitizer', '8', 'CNY', 'http://dummyimage.com/211x140.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (397, 'Premier Value', '569', 'PEN', 'http://dummyimage.com/186x165.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (398, 'ziprasidone hydrochloride', '408', 'NIO', 'http://dummyimage.com/143x166.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (399, 'Warfarin Sodium', '900', 'IDR', 'http://dummyimage.com/204x115.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (400, 'Naturasil', '3256', 'PHP', 'http://dummyimage.com/134x138.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (401, 'Cold Sore Treatment', '4', 'CZK', 'http://dummyimage.com/140x132.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (402, 'Country Gent', '7', 'KRW', 'http://dummyimage.com/156x125.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (403, 'DIVALPROEX SODIUM', '5966', 'IDR', 'http://dummyimage.com/206x171.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (404, 'Triamcinolone Acetonide', '47', 'CHF', 'http://dummyimage.com/103x130.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (405, 'Trazodone Hydrochloride', '11', 'XOF', 'http://dummyimage.com/245x159.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (406, 'Risperidone', '059', 'RUB', 'http://dummyimage.com/200x128.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (407, 'Clopidogrel', '55879', 'CNY', 'http://dummyimage.com/172x154.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (408, 'H-E-B', '05', 'IDR', 'http://dummyimage.com/180x159.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (409, 'Fetzima', '089', 'IDR', 'http://dummyimage.com/153x124.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (410, 'Anti Allergy', '809', 'VND', 'http://dummyimage.com/201x169.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (411, 'Sodium Citrate and Citric Acid', '750', 'IDR', 'http://dummyimage.com/235x171.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (412, 'Clobetasol Propionate', '92', 'CNY', 'http://dummyimage.com/244x150.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (413, 'Epsom Salt', '0862', 'IDR', 'http://dummyimage.com/183x137.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (414, 'Evista', '40974', 'BRL', 'http://dummyimage.com/242x172.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (415, 'SHISEIDO BENEFIANCE WRINKLERESIST24 DAY', '435', 'VND', 'http://dummyimage.com/237x133.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (416, 'Antiseptic', '8', 'PLN', 'http://dummyimage.com/106x164.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (417, 'Amlodipine Besylate', '417', 'EUR', 'http://dummyimage.com/120x173.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (418, 'Renvela', '9', 'CNY', 'http://dummyimage.com/102x125.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (419, 'CLARINS Broad Spectrum SPF 15 Sunscreen Extra-Firming Foundation Tint 111', '08109', 'CNY', 'http://dummyimage.com/205x158.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (420, 'Oxybutynin Chloride', '45', 'SEK', 'http://dummyimage.com/194x170.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (421, 'Black Walnut', '59229', 'BYR', 'http://dummyimage.com/190x141.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (422, 'Stemphylium sarciniforms', '361', 'IDR', 'http://dummyimage.com/241x157.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (423, 'Smart Sense Childrens Pain Relief', '76315', 'BRL', 'http://dummyimage.com/237x120.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (424, 'Sulfamethoxazole and Trimethoprim', '10', 'USD', 'http://dummyimage.com/151x142.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (425, 'Megestrol Acetate', '98', 'NPR', 'http://dummyimage.com/190x102.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (426, 'Lisinopril', '8687', 'PHP', 'http://dummyimage.com/208x159.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (427, 'Prednisone', '4005', 'EUR', 'http://dummyimage.com/222x108.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (428, 'CVS Gentle Laxative', '52323', 'CHF', 'http://dummyimage.com/177x106.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (429, 'Headache', '338', 'KGS', 'http://dummyimage.com/242x117.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (430, 'TOPIRAMATE', '64', 'EUR', 'http://dummyimage.com/203x145.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (431, 'Hog Epithelium', '55125', 'XAF', 'http://dummyimage.com/249x123.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (432, 'Diethylpropion Hydrochloride', '1', 'USD', 'http://dummyimage.com/123x108.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (433, 'Caffeic Acid', '34842', 'CUP', 'http://dummyimage.com/187x149.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (434, 'ASPERGILLUS NIGER VAR NIGER', '262', 'IDR', 'http://dummyimage.com/194x179.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (435, 'Lamivudine and Zidovudine', '67074', 'CNY', 'http://dummyimage.com/178x121.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (436, 'VITALUMIERE AQUA', '225', 'IDR', 'http://dummyimage.com/162x169.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (437, 'Walgreens SUNSCREEN', '760', 'PHP', 'http://dummyimage.com/121x106.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (438, 'mally Face Defender Foundation', '7499', 'EUR', 'http://dummyimage.com/131x152.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (439, 'Pain Reliever PM Extra Strength', '98316', 'JPY', 'http://dummyimage.com/154x103.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (440, 'OXYGEN', '14486', 'BRL', 'http://dummyimage.com/104x129.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (441, 'antacid', '447', 'CDF', 'http://dummyimage.com/216x123.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (442, 'TOPIRAMATE', '675', 'CNY', 'http://dummyimage.com/245x134.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (443, 'Dark Foundation SPF 15', '1', 'CNY', 'http://dummyimage.com/233x160.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (444, 'DE LA CRUZ GENTIAN VIOLET', '99676', 'CNY', 'http://dummyimage.com/119x124.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (445, 'Prednisone', '799', 'SEK', 'http://dummyimage.com/159x146.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (446, 'smart sense nasal', '68', 'NIO', 'http://dummyimage.com/221x178.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (447, 'SyDerm', '5467', 'CNY', 'http://dummyimage.com/105x153.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (448, 'LoHist DM', '2', 'PEN', 'http://dummyimage.com/155x123.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (449, 'Stomach Cramps 1', '2', 'MKD', 'http://dummyimage.com/147x176.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (450, 'NAAMAN', '936', 'IDR', 'http://dummyimage.com/229x148.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (451, 'Reprexain', '3', 'PHP', 'http://dummyimage.com/101x174.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (452, 'No7 Lifting and Firming Foundation Sunscreen SPF 15 Truffle', '23684', 'CNY', 'http://dummyimage.com/164x146.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (453, 'SEROQUEL', '34', 'EUR', 'http://dummyimage.com/120x172.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (454, 'Diphenhydramine HCl', '82', 'XAF', 'http://dummyimage.com/133x129.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (455, 'Pravastatin Sodium', '653', 'HRK', 'http://dummyimage.com/105x148.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (456, 'OXYGEN', '375', 'SEK', 'http://dummyimage.com/133x167.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (457, 'Lorazepam', '82790', 'LSL', 'http://dummyimage.com/101x129.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (458, 'Cilostazol', '46058', 'CNY', 'http://dummyimage.com/152x166.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (459, 'Sodium FluorideF 18', '68478', 'NGN', 'http://dummyimage.com/122x171.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (460, 'acid reducer', '788', 'IRR', 'http://dummyimage.com/186x177.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (461, 'Arnica Cream', '73217', 'ALL', 'http://dummyimage.com/136x101.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (462, 'IPECACUANHA', '81755', 'CNY', 'http://dummyimage.com/145x158.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (463, 'Lidocaine Hydrochloride', '3', 'HNL', 'http://dummyimage.com/212x149.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (464, 'Cefpodoxime Proxetil', '56625', 'EUR', 'http://dummyimage.com/101x169.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (465, 'Alprazolam', '377', 'COP', 'http://dummyimage.com/190x173.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (466, 'Doxepin Hydrochloride', '355', 'RUB', 'http://dummyimage.com/118x179.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (467, 'Pain Relief', '9', 'CNY', 'http://dummyimage.com/179x141.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (468, 'Sertraline Hydrochloride', '4340', 'SEK', 'http://dummyimage.com/115x114.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (469, 'Oxygen', '8', 'IDR', 'http://dummyimage.com/143x144.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (470, 'LBEL Couleur Luxe Rouge Amplifier XP amplifying SPF 15', '36', 'IDR', 'http://dummyimage.com/187x140.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (471, 'Dolce and Gabbana The Lift Foundation Creamy 80', '490', 'PLN', 'http://dummyimage.com/228x140.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (472, 'rexall anti itch', '00374', 'PHP', 'http://dummyimage.com/127x158.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (473, 'SUNFLOWER SEED', '39', 'PLN', 'http://dummyimage.com/236x166.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (474, 'GALANTAMINE HYDROBROMIDE', '60707', 'SEK', 'http://dummyimage.com/144x143.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (475, 'SENSAI SILKY BRONZE SUN PROTECTIVE CREAM FOR FACE SPF30', '49060', 'USD', 'http://dummyimage.com/208x148.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (476, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', '88', 'ZWL', 'http://dummyimage.com/171x176.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (477, 'MedPride', '286', 'AZN', 'http://dummyimage.com/104x151.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (478, 'Rye Grain', '8733', 'EUR', 'http://dummyimage.com/124x170.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (479, 'Etomidate', '67', 'PLN', 'http://dummyimage.com/218x141.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (480, 'Diastat', '675', 'PEN', 'http://dummyimage.com/218x175.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (481, 'health mart adult tussin', '11187', 'SYP', 'http://dummyimage.com/191x176.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (482, 'HUNGARIAN SMOOTH BROME POLLEN', '32858', 'IDR', 'http://dummyimage.com/161x133.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (483, 'SEAWEED MEDICLEAR MASK', '61751', 'RUB', 'http://dummyimage.com/158x135.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (484, 'Banana Boat Ultra Defence SPF 30 for UK', '0217', 'XOF', 'http://dummyimage.com/194x171.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (485, 'Biofreeze Colorless Roll-On', '9', 'EUR', 'http://dummyimage.com/107x137.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (486, 'Povidone-Iodine Prep', '49253', 'CZK', 'http://dummyimage.com/199x174.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (487, 'Metformin Hydrochloride', '2236', 'RUB', 'http://dummyimage.com/200x102.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (488, 'Nitrogen', '4046', 'EUR', 'http://dummyimage.com/110x170.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (489, 'Neova DNA Damage Control - Silc Sheer', '3376', 'JPY', 'http://dummyimage.com/135x127.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (490, 'Adrenaclick', '13', 'EUR', 'http://dummyimage.com/142x157.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (491, 'Lopid', '996', 'EUR', 'http://dummyimage.com/153x136.png/cc0000/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (492, 'PAIN Terminator Analgesic', '13852', 'GHS', 'http://dummyimage.com/147x134.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (493, 'Chlordiazepoxide Hydrochloride', '56', 'IDR', 'http://dummyimage.com/235x139.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (494, 'Ceftriaxone Sodium', '06839', 'VEF', 'http://dummyimage.com/206x154.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (495, 'Sysco', '3', 'CNY', 'http://dummyimage.com/127x114.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (496, 'IMITREX', '36421', 'LTL', 'http://dummyimage.com/229x180.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (497, 'CLE DE PEAU BEAUTE FOUNDATION L', '8', 'LAK', 'http://dummyimage.com/103x123.png/ff4444/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (498, 'New Skin Bandage', '9', 'UGX', 'http://dummyimage.com/112x110.png/5fa2dd/ffffff');
insert into products (idproducts, name, montant, devise, imageUrl) values (499, 'Lyrica', '71663', 'ALL', 'http://dummyimage.com/150x114.png/dddddd/000000');
insert into products (idproducts, name, montant, devise, imageUrl) values (500, 'Low Dose Aspirin', '6', 'MYR', 'http://dummyimage.com/248x120.png/dddddd/000000');
